name: api_trial
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2 # For API calls
  flutter_dotenv: ^6.0.0 # For .env API key
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  cached_network_image: ^3.3.1
  supabase_flutter: ^2.9.1
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  cunning_document_scanner: ^1.2.2
  path_provider: ^2.1.5
  device_info_plus: ^11.5.0
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_language_id: ^0.13.0
  image: ^4.5.4
  camera: ^0.11.2
  ffi: ^2.1.4

  opencv_dart:
    path: third_party/opencv_dart-1.4.3

dependency_overrides:
  dartcv4:
    path: third_party/dartcv4-1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.12
  freezed: ^3.2.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
